Last login: Tue Apr 30 17:16:06 on ttys002
MacBook-Air-108:~ stripp$ cd Desktop/
MacBook-Air-108:Desktop stripp$ chmod +x Hearts
MacBook-Air-108:Desktop stripp$ ./Hearts 
Connected.
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1705, in __call__
  File "tkinter/__init__.py", line 749, in callit
  File "GUI.py", line 172, in poll_loop
  File "GUI.py", line 321, in show_card
KeyError: '3ct:samh:4c'

MacBook-Air-108:Desktop stripp$ ./Hearts 
Connected.
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1705, in __call__
  File "tkinter/__init__.py", line 749, in callit
  File "GUI.py", line 176, in poll_loop
  File "GUI.py", line 81, in end_trick
ValueError: 'byronh:7c' is not in list